name: Publish

on:
  schedule:
    - cron: "0 4 * * *"

concurrency: publish

jobs:

  publish:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: 84tech
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: docker build
        run: |
          VERSION=$(cargo search minhtml --limit 1 |  head -n 1 | cut -d ' ' -f3 | tr -d '"')
          docker buildx create --use
          docker buildx build --push -t 84tech/minhtml:latest -t 84tech/minhtml:$VERSION --build-arg MINHTML_VERSION=$VERSION --platform linux/amd64,linux/arm64 .
